<?php

return [
    'height' => (function () {
        $arr = ['below' => 'Below 122 cm'];
        for ($i = 122; $i <= 213; $i++) {
            $arr[(string)$i] = "{$i} cm";
        }
        $arr['above'] = 'Above 213 cm';
        return $arr;
    })(),
    'country' => [
        'Afghanistan',
        'Albania',
        'Algeria',
        'Andorra',
        'Angola',
        'Antigua and Barbuda',
        'Argentina',
        'Armenia',
        'Australia',
        'Austria',
        'Azerbaijan',
        'Bahamas',
        'Bahrain',
        'Bangladesh',
        'Barbados',
        'Belgium',
        'Belize',
        'Belarus',
        'Benin',
        'Botswana',
        'Bulgaria',
        'Bolivia',
        'Bosnia and Herzegovina',
        'Brazil',
        'Brunei',
        'Burkina Faso',
        'Burundi',
        'Bhutan',
        'Cyprus',
        'Chad',
        'Czech Republic',
        'Chile',
        'Denmark',
        'Dominica',
        'Dominican Republic',
        'Djibouti',
        'Egypt',
        'Ecuador',
        'Equatorial Guinea',
        'Eritrea',
        'Estonia',
        'Ethiopia',
        'Fiji',
        'Philippines',
        'Finland',
        'France',
        'Gabon',
        'Gambia',
        'Ghana',
        'Greece',
        'Grenada',
        'Georgia',
        'Guyana',
        'Guatemala',
        'Guinea',
        'Guinea-Bissau',
        'Haiti',
        'Honduras',
        'Croatia',
        'India',
        'Indonesia',
        'Iraq',
        'Iran',
        'Ireland',
        'Iceland',
        'Italy',
        'Israel',
        'Jamaica',
        'Japan',
        'Yemen',
        'Jordan',
        'Yugoslavia',
        'South Africa',
        'South Korea',
        'Cambodia',
        'Cameroon',
        'Canada',
        'Qatar',
        'Kazakhstan',
        'Kenya',
        'Kyrgyzstan',
        'Kiribati',
        'China',
        'Colombia',
        'Comoros',
        'Congo',
        'Costa Rica',
        'Cuba',
        'Kuwait',
        'Laos',
        'Latvia',
        'Lesotho',
        'Lebanon',
        'Liberia',
        'Libya',
        'Liechtenstein',
        'Lithuania',
        'Luxembourg',
        'Madagascar',
        'Hungary',
        'Macedonia',
        'Malawi',
        'Maldives',
        'Malaysia',
        'Mali',
        'Malta',
        'Morocco',
        'Marshall Islands',
        'Mauritius',
        'Mauritania',
        'Mexico',
        'Micronesia',
        'Myanmar',
        'Moldavia',
        'Monaco',
        'Mongolia',
        'Montserrat',
        'Mozambique',
        'Namibia',
        'Nauru',
        'Germany',
        'Nepal',
        'Niger',
        'Nigeria',
        'Nicaragua',
        'Netherlands',
        'Norway',
        'New Zealand',
        'Oman',
        'Pakistan',
        'Palau',
        'Panama',
        'Papua New Guinea',
        'Paraguay',
        'Peru',
        'Poland',
        'Puerto Rico',
        'Portugal',
        'Romania',
        'Rwanda',
        'Russia',
        'Saint Kitts in Nevis',
        'Saint Lucia',
        'Saint Vincent and the Grenadines',
        'Solomon Islands',
        'Salvador',
        'San Marino',
        'Sao Tome and Principe',
        'Saudi Arabia',
        'Seychelles',
        'Senegal',
        'North Korea',
        'Northern Mariana Islands',
        'Sierra Leone',
        'Singapore',
        'Syria',
        'Ivory Coast',
        'Slovakia',
        'Slovenia',
        'Somalia',
        'Central African Republic',
        'Sudan',
        'Suriname',
        'Swaziland',
        'Spain',
        'Sri Lanka',
        'Sweden',
        'Switzerland',
        'Tajikistan',
        'Thailand',
        'Taiwan',
        'Tanzania',
        'Togo',
        'Tonga',
        'Trinidad and Tobago',
        'Tunisia',
        'Turkey',
        'Turkmenistan',
        'Tuvalu',
        'Uganda',
        'Ukraine',
        'Uruguay',
        'Uzbekistan',
        'Vanuatu',
        'Vatican',
        'United Kingdom',
        'Venezuela',
        'Vietnam',
        'Western Sahara',
        'Zaire',
        'Zambia',
        'United States of America',
        'United Arab Emirates',
        'Cape Verde',
        'Zimbabwe',
    ],
    'document_type' => [
        'National ID card',
        'International Passport',
        "Government-issued Driver's License"
    ],
    'gender' => [
        'Male',
        'Female'
    ],
    'body_type' => [
        'Skinny',
        'Average',
        'Athletic',
        'Body Builder',
        'A few extra pounds',
        'Stronger',
        "I don't want to say ..."
    ],
    'eye_color' => [
        'Green',
        'Blue',
        'Black',
        'Grey',
        'Brown',
        "Don't know",
    ],
    'hair_color' => [
        'Brown',
        'Black',
        'Gray',
        'Blonde',
        'Red',
        'Shaved',
        'Other'
    ],
    'sleeping_habits' => [
        'I go to bed early (before 10pm)',
        'I go to bed late (after midnight)',
        'I have an irregular sleep schedule',
        'I prefer to sleep alone',
        'I love sleeping with a partner',
        'I need complete silence',
        'I need some background noise',
        'I have a bedtime ritual (e.g., reading, listening to music)',
        'I just fall asleep, no routine',
        'I meditate before bed',
    ],

    'love_language' => [
        'Words of Affirmation',
        'Acts of Service',
        'Receiving Gifts',
        'Quality Time',
        'Physical Touch',
    ],
    'childrean' => [
        "I don't have children",
        'I have children',
        'Maybe',
        "I don't want children",
        "I don't know yet ...",
        "I have and I don't want any more",
        'I have and I want more',
    ],
    'financial_status' => [
        'Excellent',
        'Very satisfactory',
        'Average',
        'Not the best',
        'A hole in the wallet',
    ],
    'dress_stype' => [
        'Casual',
        'Trendy',
        'Fine',
        'Urban',
        'Business',
        'Sports',
        'Fashion',
        'Alternative',
        'Retro',
        'Other',
    ],
    'pets' => [
        'Dog',
        'Cat',
        'Fish',
        'Horse',
        'Birds',
        'Reptiles',
        'Spiders',
        'Other animals',
        'Rodents',
        "I don't have a pet",
    ],
    'zodiac_sign' => [
        'Aries',
        'Taurus',
        'Gemini',
        'Cancer',
        'Leo',
        'Virgo',
        'Libra',
        'Scorpio',
        'Capricorn',
        'Aquarius',
        'Pisces',
//        'Sagittarius',
    ],
    'vaccinated' => [
        'Yes - Fully Vaccinated',
        'Yes - Partially Vaccinated',
        'No',
        'Prefer not to say',
    ],
    'drinking_habits' => [
        'I drink alcohol regularly',
        "I don't drink alcohol",
        'I drink alcohol occasionally',
        "I don't want to say ...",
//        'Never',
//        'Occasionally',
//        'Social Drinker',
//        'Regularly',
//        'Trying to Quit',
    ],
    'smoking_habits' => [
        "I don't smoke",
        'I smoke',
        "I'm trying to quit",
        'Occasionally',
        "I don't want to say ...",
//        'Non-smoker',
//        'Occasionally',
//        'Social Smoker',
//        'Regularly',
//        'Trying to Quit',
    ],
    'eating_habits' => [
        "I don't want to say ...",
        'Mostly healthy',
        'Health-conscious',
        'Vegetarian',
        'Vegan',
        'Pescatarian',
        'Flexitarian',
        'Keto/Low-carb',
        'Organic food lover',
        'Fast food fan',
        'Gluten-free',
        'Lactose-free',
        'Balanced diet',
        'Home-cooked meals preferred',
        'Intermittent fasting',
        'No dietary restrictions',
        'Foodie – I love trying new cuisines',
        'Selective eater / Picky eater',
        'Meal prep enthusiast',
        'Enjoys dining out regularly',
    ],
    'communication_style' => [
        'Long phone calls',
        'Short phone calls',
        'Texting throughout the day',
        'Occasional texting',
        'Voice messages',
        'Video calls',
        'In-person conversations preferred',
        'I’m not much of a talker',
        'I reply when I can',
        'Prefer not to say',
    ],
    'workout' => [
        'Daily',
        'A few times a week',
        'Occasionally',
        'Rarely',
        'Never',
        'Fitness is a big part of my life',
        'I prefer outdoor activities',
        'Only when I feel like it',
        'I’m just getting started',
        'Prefer not to say',
    ],
    'education' => [
        'Elementary school',
        'Secondary school',
        'College',
        'University education',
        "Master's degree",
        'Doctorate',
        'Other',
    ],
    'occupation' => [
        'Unemployed',
        'Employed',
        'Temporary',
        'Student',
        'Self-employed',
        'Retired',
        'Other',
    ],
    'language_speak' => [
        'English',
        'Bosnian',
        'Bulgarian',
        'Chinese',
        'Croatian',
        'Czech',
        'Danish',
        'Estonian',
        'Finnish',
        'French',
        'German',
        'Hungarian',
        'Italian',
        'Polish',
        'Romanian',
        'Russian',
        'Serbian',
        'Slovak',
        'Slovenian',
        'Spanish',
        'Swedish',
        'Ukrainian',
        'Other',
    ],
    'relationship_status' => [
        'Single',
        'In a Relationship',
        'Divorced',
        'Widower',
        'Lover',
        "I don't want to say ...",
        "It's complicated",
        'Other',
    ],
    'religion' => [
        'Christianity',
        'Islam',
        'Hinduism',
        'Buddhism',
        'Judaism',
        'Atheist',
        'Agnostic',
        'Other',
    ],
    'location' => [
        'Urban',
        'Suburban',
        'Rural',
    ],
    'sports' => [
        'Skiing',
        'Hiking',
        'Soccer',
        'Basketball',
        'Tennis',
        'Volleyball',
        'Baseball',
        'Swimming',
        'Athletics',
        'Boxing',
        'Rugby',
        'American Football',
        'Ice Hockey',
        'Golf',
        'Table Tennis',
        'Badminton',
        'Martial Arts',
        'Cycling',
        'Gymnastics',
        'Surfing',
    ],
    'entertainment' => [
        'Cooking',
        'Travel',
        'Music',
        'Concerts',
        'Nature',
        'Social Media',
        'Dance',
        'Art Creation',
        'Film & Television',
        'Museums & Exhibitions',
        'Home Improvement',
        'Gardening',
        'Writing',
        'Books & Literature',
        'Internet',
        'Socializing',
        'Cars',
        'Motorcycles',
        'Motorboating',
        'Sailing',
        'Video Games',
        'Photography',
        'Singing',
        'Playing Instruments',
        'Culture',
        'Arts',
        'Board Games',
        'Charity',
        'Fashion & Beauty',
        'Health & Wellness',
        'Hobbies',
        'Do It Yourself',
        'Fishing',
        'Theater',
        'Beach & Sea',
        'Animals',
        'Sewing',
        'History',
        'Astrology',
        'Outdoor Activities',
        'Relaxation',
        'Education',
        'Kids & Family',
        'Other',
    ],
    'my_interests' => [
        'Friendship',
        'Date',
        'Marriage',
        'Adventure',
        'Intimate encounter',
        'Short term',
        'Long term',
        'Anything',
        "I don't know yet ...",
    ],
    'iam_looking_for' => [
        'Friendship',
        'Dating',
        'Marriage',
        'Adventure',
        'Intimate encounter',
        'Short term',
        'Anything',
        "I don't know yet ...",
    ],
    'iam_seeking' => [
        'Man',
        'Woman',
        'Couple',
        'No Preference',
    ],
    'partner_children' => [
        'No children',
        'Have children',
        'Maybe',
    ]
];
