<?php

return [
    'height' => (function () {
        $arr = ['below' => 'Below 122 cm'];
        for ($i = 122; $i <= 213; $i++) {
            $arr[(string) $i] = "{$i} cm";
        }
        $arr['above'] = 'Above 213 cm';
        return $arr;
    })(),
    'country' => [
        'India',
        'USA',
        'Canada',
        'Germany',
        'Australia',
        'UK',
        'France',
        'Japan',
        'China',
        'Brazil'
    ],
    'document_type' => [
        'National ID card',
        'International Passport',
        "Government-issued Driver's License"
    ],
    'gender' => [
        'Male',
        'Women'
    ],
    'body_type' => [
        'Slim',
        'Athletic',
        'Average',
        'Curvy',
        'Plus Size',
        'Muscular',
        'Chubby',
    ],
    'eye_color' => [
        'Green',
        'Blue',
        'Black',
        'Grey',
        'Brown',
        "Don't know",
    ],
    'hair_color' => [
        'Black',
        'Brown',
        'Blonde',
        'Red',
        'Gray',
        'White',
        'Bald',
    ],
    'sleeping_habits' => [
        'Night Owl',
        'Early Bird',
    ],
    'love_language' => [
        'Words of Affirmation',
        'Acts of Service',
        'Receiving Gifts',
        'Quality Time',
        'Physical Touch',
    ],
    'childrean' => [
        "I don't have children",
        'I have children',
        'Maybe',
        "I don't want children",
        "I don't know yet ...",
        "I have and I don't want any more",
        'I have and I want more',
    ],
    'financial_status' => [
        'Excellent',
        'Very satisfactory',
        'Average',
        'Not the best',
        'A hole in the wallet',
    ],
    'dress_stype' => [
        'Casual',
        'Trendy',
        'Fine',
        'Urban',
        'Business',
        'Sports',
        'Fashion',
        'Alternative',
        'Retro',
        'Other',
    ],
    'pets' => [
        'Dog',
        'Cat',
        'Fish',
        'Horse',
        'Birds',
        'Reptiles',
        'Spiders',
        'Other animals',
        'Rodents',
        "I don't have a pet",
    ],
    'zodiac_sign' => [
        'Aries',
        'Taurus',
        'Gemini',
        'Cancer',
        'Leo',
        'Virgo',
        'Libra',
        'Scorpio',
        'Sagittarius',
        'Capricorn',
        'Aquarius',
        'Pisces',
    ],
    'vaccinated' => [
        'Yes - Fully Vaccinated',
        'Yes - Partially Vaccinated',
        'No',
        'Prefer not to say',
    ],
    'drinking_habits' => [
        'Never',
        'Occasionally',
        'Social Drinker',
        'Regularly',
        'Trying to Quit',
    ],
    'smoking_habits' => [
        'Non-smoker',
        'Occasionally',
        'Social Smoker',
        'Regularly',
        'Trying to Quit',
    ],
    'eating_habits' => [
        "I don't want to say ...",
        'Mostly healthy',
        'Health-conscious',
        'Vegetarian',
        'Vegan',
        'Pescatarian',
        'Flexitarian',
        'Keto/Low-carb',
        'Organic food lover',
        'Fast food fan',
        'Gluten-free',
        'Lactose-free',
        'Balanced diet',
        'Home-cooked meals preferred',
        'Intermittent fasting',
        'No dietary restrictions',
        'Foodie – I love trying new cuisines',
        'Selective eater / Picky eater',
        'Meal prep enthusiast',
        'Enjoys dining out regularly',
    ],
    'communication_style' => [
        'Long phone calls',
        'Short phone calls',
        'Texting throughout the day',
        'Occasional texting',
        'Voice messages',
        'Video calls',
        'In-person conversations preferred',
        'I’m not much of a talker',
        'I reply when I can',
        'Prefer not to say',
    ],
    'workout' => [
        'Daily',
        'A few times a week',
        'Occasionally',
        'Rarely',
        'Never',
        'Fitness is a big part of my life',
        'I prefer outdoor activities',
        'Only when I feel like it',
        'I’m just getting started',
        'Prefer not to say',
    ],
    'education' => [
        'Elementary school',
        'Secondary school',
        'College',
        'University education',
        "Master's degree",
        'Doctorate',
        'Other',
    ],
    'occupation' => [
        'Unemployed',
        'Employed',
        'Temporary',
        'Student',
        'Self-employed',
        'Retired',
        'Other',
    ],
    'language_speak' => [
        'English',
        'Spanish',
        'French',
        'German',
        'Mandarin',
        'Other',
    ],
    'relationship_status' => [
        'Single',
        'In a Relationship',
        'Engaged',
        'Married',
        'Divorced',
        'Widowed',
    ],
    'religion' => [
        'Christianity',
        'Islam',
        'Hinduism',
        'Buddhism',
        'Judaism',
        'Other',
        'Prefer not to say',
    ],
    'location' => [
        'Urban',
        'Suburban',
        'Rural',
    ],
    'sports' => [
        'Skiing',
        'Hiking',
        'Soccer',
        'Basketball',
        'Tennis',
        'Volleyball',
        'Baseball',
        'Swimming',
        'Athletics',
        'Boxing',
        'Rugby',
        'American Football',
        'Ice Hockey',
        'Golf',
        'Table Tennis',
        'Badminton',
        'Martial Arts',
        'Cycling',
        'Gymnastics',
        'Surfing',
    ],
    'entertainment' => [
        'Cooking',
        'Travel',
        'Music',
        'Concerts',
        'Nature',
        'Social Media',
        'Dance',
        'Art Creation',
        'Film & Television',
        'Museums & Exhibitions',
        'Home Improvement',
        'Gardening',
        'Writing',
        'Books & Literature',
        'Internet',
        'Socializing',
        'Cars',
        'Motorcycles',
        'Motorboating',
        'Sailing',
        'Video Games',
        'Photography',
        'Singing',
        'Playing Instruments',
        'Culture',
        'Arts',
        'Board Games',
        'Charity',
        'Fashion & Beauty',
        'Health & Wellness',
        'Hobbies',
        'Do It Yourself',
        'Fishing',
        'Theater',
        'Beach & Sea',
        'Animals',
        'Sewing',
        'History',
        'Astrology',
        'Outdoor Activities',
        'Relaxation',
        'Education',
        'Kids & Family',
        'Other',
    ],
    'my_interests' => [
        'Friendship',
        'Dating',
        'Marriage',
        'Adventure',
        'Intimate encounter',
        'Short term',
        'Anything',
        "I don't know yet ...",
    ],
    'iam_looking_for' => [
        'Friendship',
        'Dating',
        'Marriage',
        'Adventure',
        'Intimate encounter',
        'Short term',
        'Anything',
        "I don't know yet ...",
    ],
    'iam_seeking' => [
        'Man',
        'Woman',
        'Couple',
        'No Preference',
    ],
    'partner_children' => [
            'No children',
            'Have children',
            'Maybe',
    ]
];
